openneuro_ds005884_cospine_motor: datasets/openneuro_ds005884_cospine_motor
openneuro_ds005883_cospine_pain: datasets/openneuro_ds005883_cospine_pain
openneuro_ds004386_spinalcord_rest_testretest: datasets/openneuro_ds004386_spinalcord_rest_testretest
openneuro_ds004616_spinalcord_handgrasp_task: datasets/openneuro_ds004616_spinalcord_handgrasp_task
internal_balgrist_motor_11: /mnt/ssd1/SpinalfMRIprep/datasets/internal_balgrist_motor_11
reg_openneuro_ds005884_cospine_motor_subset: datasets/openneuro_ds005884_cospine_motor
reg_openneuro_ds004386_rest_subset: datasets/openneuro_ds004386_spinalcord_rest_testretest
reg_openneuro_ds005883_cospine_pain_subset: datasets/openneuro_ds005883_cospine_pain
reg_openneuro_ds004616_handgrasp_subset: datasets/openneuro_ds004616_spinalcord_handgrasp_task
reg_internal_balgrist_motor_11_subset: /mnt/ssd1/SpinalfMRIprep/datasets/internal_balgrist_motor_11